version: '3.8'

services:
  web:
    build:
      context: ./be
      dockerfile: Dockerfile  
    restart: always
    command: uvicorn be.asgi:application --host 0.0.0.0 --port 8000 --reload  
    environment:
      - DJANGO_SETTINGS_MODULE=be.settings 
    volumes:
      - ./be:/code 
    ports:
      - "8000:8000"
