[build]
  context = "./be/be"          # Tell Railway to look inside the actual Django project folder.
  builder = "python"           # We are building a Python app.

[deploy]
  start = "pip install -r requirements.txt && gunicorn be.wsgi --chdir be --log-file -"  # Use the correct project name
