# Railway.toml for the backend
[build]
  builder = "heroku/python"  # For the backend (assuming Django)
  path = "be"  # Backend directory

# For frontend (if deploying separately or in a multi-service setup)
[[services]]
  name = "frontend"
  build = "fe"
  env = "production"
  command = "npm run build"  # Build frontend assets
  port = 80
