# Generated by Django 5.1.2 on 2024-12-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_student_studentexample'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexample',
            name='attempts',
            field=models.IntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='studentexample',
            constraint=models.UniqueConstraint(fields=('student', 'example', 'date'), name='unique_student_example_date'),
        ),
    ]
