# Generated by Django 5.1.2 on 2024-12-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_studentexample_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexample',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
