# Generated by Django 5.1.4 on 2024-12-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_studentexample_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexample',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
