# Generated by Django 5.1.4 on 2025-01-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_studentexample_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexample',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
    ]
