# Generated by Django 5.1.4 on 2025-01-31 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_studentexample_skipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='parent_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subskills', to='api.skill'),
        ),
    ]
