# Generated by Django 5.1.4 on 2025-02-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_skill_parent_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(blank=True, choices=[('OPERATION', 'Operation'), ('NUMBER_DOMAIN', 'Number Domain')], max_length=50, null=True),
        ),
    ]
