# Generated by Django 5.1.4 on 2025-02-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_skill_skill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='related_skills',
            field=models.ManyToManyField(blank=True, to='api.skill'),
        ),
    ]
