# Generated by Django 5.1.4 on 2025-02-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_skill_related_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='api.skill'),
        ),
    ]
