# Generated by Django 5.1.4 on 2025-02-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexample',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
