# Generated by Django 5.1.4 on 2025-02-17 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_studentexample_solved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.example')),
            ],
        ),
    ]
