# Generated by Django 5.1.4 on 2025-03-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='form',
            field=models.CharField(choices=[('classic', 'Classic'), ('word-problem', 'Word Problem')], default='classic', max_length=20),
        ),
    ]
