# Generated by Django 5.1.4 on 2025-03-12 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_task_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_data', models.BinaryField()),
                ('transcription', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('example', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.example')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
    ]
