# Generated by Django 5.1.4 on 2025-03-20 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_skill_deleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioPrompt',
        ),
    ]
