version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: uvicorn be.asgi:application --host 0.0.0.0 --port 8000 --reload
    environment:
      - DJANGO_SETTINGS_MODULE=be.settings
      - MYSQLHOST=db
      - MYSQLUSER=root
      - MYSQLPASSWORD=secret
      - MYSQLDATABASE=drillovacka-demo
      - MYSQLPORT=3306
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: drillovacka-demo
    ports:
      - "3307:3306"  
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d  

volumes:
  db_data:
