version: '3.8'

services:
  web:
    build:
      context: .  # The build context should be the root of your project, where the Dockerfile is located
      dockerfile: Dockerfile  # Explicitly specify the Dockerfile if needed
    restart: always
    command: uvicorn be.asgi:application --host 0.0.0.0 --port 8000 --reload
    environment:
      - DJANGO_SETTINGS_MODULE=be.settings  # Make sure this points to the correct settings module
    volumes:
      - .:/code  # Mount the 'be' folder to /code in the container
    ports:
      - "8000:8000"  # Expose port 8000
